import { pgTable, uuid, text, integer, timestamp, pgEnum, jsonb } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { users } from './users';
import { courses, lessons } from './courses';

// Enums
export const progressStatusEnum = pgEnum('progress_status', ['in_progress', 'completed']);

// User Progress Table
export const userProgress = pgTable('user_progress', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  courseId: uuid('course_id')
    .references(() => courses.id, { onDelete: 'cascade' })
    .notNull(),
  lessonId: uuid('lesson_id')
    .references(() => lessons.id, { onDelete: 'cascade' })
    .notNull(),
  status: progressStatusEnum('status').default('completed').notNull(),
  completedAt: timestamp('completed_at').defaultNow().notNull(),
});

// Quizzes Table
export const quizzes = pgTable('quizzes', {
  id: uuid('id').defaultRandom().primaryKey(),
  lessonId: uuid('lesson_id')
    .references(() => lessons.id, { onDelete: 'cascade' })
    .notNull()
    .unique(), // One quiz per quiz-type lesson
  title: text('title').notNull(),
  passingScore: integer('passing_score').default(60).notNull(), // Percentage required, e.g. 60%
  timeLimitSeconds: integer('time_limit_seconds').default(0).notNull(), // 0 for unlimited
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Quiz Questions Table
export const quizQuestions = pgTable('quiz_questions', {
  id: uuid('id').defaultRandom().primaryKey(),
  quizId: uuid('quiz_id')
    .references(() => quizzes.id, { onDelete: 'cascade' })
    .notNull(),
  text: text('text').notNull(),
  options: jsonb('options').$type<string[]>().notNull(), // Array of choices
  correctAnswer: text('correct_answer').notNull(), // Must match one of the choices exactly
  explanation: text('explanation'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Quiz Attempts Table
export const quizAttempts = pgTable('quiz_attempts', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  quizId: uuid('quiz_id')
    .references(() => quizzes.id, { onDelete: 'cascade' })
    .notNull(),
  score: integer('score').notNull(), // Final percentage score (0-100)
  answers: jsonb('answers').$type<Record<string, string>>().notNull(), // Map of questionId -> userSelectedChoice
  aiFeedback: text('ai_feedback'), // Contextual feedback generated by LLM
  startedAt: timestamp('started_at').defaultNow().notNull(),
  completedAt: timestamp('completed_at').defaultNow().notNull(),
});

// Learning Streaks Table
export const learningStreaks = pgTable('learning_streaks', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull()
    .unique(),
  currentStreak: integer('current_streak').default(0).notNull(),
  longestStreak: integer('longest_streak').default(0).notNull(),
  lastActiveDate: timestamp('last_active_date'),
});

// Badges Definition Table
export const badges = pgTable('badges', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull().unique(),
  description: text('description').notNull(),
  iconUrl: text('icon_url').notNull(),
  criteriaType: text('criteria_type').notNull(), // 'streak', 'course_complete', 'quiz_perfect', etc.
  criteriaValue: integer('criteria_value').notNull(), // e.g. 7 (days streak), 1 (course)
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// User Earned Badges Table
export const userBadges = pgTable('user_badges', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  badgeId: uuid('badge_id')
    .references(() => badges.id, { onDelete: 'cascade' })
    .notNull(),
  earnedAt: timestamp('earned_at').defaultNow().notNull(),
});

// Relations
export const userProgressRelations = relations(userProgress, ({ one }) => ({
  user: one(users, {
    fields: [userProgress.userId],
    references: [users.id],
  }),
  course: one(courses, {
    fields: [userProgress.courseId],
    references: [courses.id],
  }),
  lesson: one(lessons, {
    fields: [userProgress.lessonId],
    references: [lessons.id],
  }),
}));

export const quizzesRelations = relations(quizzes, ({ one, many }) => ({
  lesson: one(lessons, {
    fields: [quizzes.lessonId],
    references: [lessons.id],
  }),
  questions: many(quizQuestions),
  attempts: many(quizAttempts),
}));

export const quizQuestionsRelations = relations(quizQuestions, ({ one }) => ({
  quiz: one(quizzes, {
    fields: [quizQuestions.quizId],
    references: [quizzes.id],
  }),
}));

export const quizAttemptsRelations = relations(quizAttempts, ({ one }) => ({
  user: one(users, {
    fields: [quizAttempts.userId],
    references: [users.id],
  }),
  quiz: one(quizzes, {
    fields: [quizAttempts.quizId],
    references: [quizzes.id],
  }),
}));

export const learningStreaksRelations = relations(learningStreaks, ({ one }) => ({
  user: one(users, {
    fields: [learningStreaks.userId],
    references: [users.id],
  }),
}));

export const userBadgesRelations = relations(userBadges, ({ one }) => ({
  user: one(users, {
    fields: [userBadges.userId],
    references: [users.id],
  }),
  badge: one(badges, {
    fields: [userBadges.badgeId],
    references: [badges.id],
  }),
}));
